### ISSUE TITLE
Start with Glamrock's Data Broker guide for Personal Data Liberation Project

### ISSUE THREAD

**Issue by dazzaji** [mitmedialab/MITLegalForum#3]
https://github.com/glamrock/data-brokers

Let's see how many of these data brokers are directly (or indirectly) subject to "subject access" requests to turn over the personal data back to those whom it is from and/or about.

Yay @Glamrock!

**Comment by glamrock** [comment]
Ohai! I opened #4 right after this :D

**Comment by dazzaji** [comment]
Thanks @glamrock!  Merging this issue into #4 :-)
